### ISSUE TITLE
documents needed

### ISSUE THREAD

**Issue by MrwuGohead** [irenjie/Phase-Measuring-Deflectometry#1]
Could I get some documents about theory？

**Comment by irenjie** [comment]
Paper "Review of phase measuring deflectometry" should help.

**Comment by MrwuGohead** [comment]
Thank you very much!

**Comment by MrwuGohead** [comment]
Hi， I am sorry to disturb you again. About paper "Review of phase measuring deflectometry", could you explain the meaing of spatial resolution and angular resolution? I could not undersand why they will interract on each other.

2.2. Image acquisition
In PMD measurement, a camera captures the reflection of the patterns displayed on a screen through the specimen surface. There is a
trade-off between the spatial resolution and the angular resolution in
image acquisition. If the camera is focused on the specimen surface, the
measurement gets the best spatial resolution, but the angular resolution
will not be the optimum due to the defocusing of the screen patterns.

**Comment by irenjie** [comment]
> 

My understanding is that spatial resolution represents the details of the SUT in the captured pictures, and angular resolution represents the details of the rays(screen patterns reflected by the SUT).

**Comment by MrwuGohead** [comment]
Ok, I think it's right. Thank you very much!
