### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by MrwuGohead** [irenjie/Phase-Measuring-Deflectometry#2]
This function ‘bool pattern_gen(std::vector<uint8_t> pat_size, std::vector<uint8_t> period, std::vector<MatrixXf>& pats)’ maybe loss in 
'algorithm_PMD.cpp'.

**Comment by MrwuGohead** [comment]
The line 655 of mainwindow.cpp should be Y not y ?

**Comment by irenjie** [comment]
1. I have generated the fringe patterns in other ways，so this method is no longer needed.
2. You are right, this is a mistake.

**Comment by MrwuGohead** [comment]
Ok, I got it. Thank you ...
