### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by MrwuGohead** [irenjie/Phase-Measuring-Deflectometry#3]
Hi, could I  ask a question that why the fringe space between black and white of the image  I got is  different with the pattern displayed on the screen ? @irenjie 
![7](https://user-images.githubusercontent.com/37230965/170922988-b25af927-9b8d-4a67-b06a-f501007abcd5.jpg)
![7-screen](https://user-images.githubusercontent.com/37230965/170923069-11c6e224-a46b-4bca-ae1f-6d9da4de5a4c.jpg)
?

**Comment by irenjie** [comment]
如果你是想问为什么条纹扭曲了，那是因为SUT的形状导致的。如果你是想问为什么SUT上的条纹和屏幕中的不一样，我也没想清楚，关于结构光技术的文章我也没看过多少。我猜可能是因为条纹灰度值范围太大，相机采集不全，导致黑的比白的多或者白的比黑的多，你可以尝试缩小这个灰度值范围(例如从0-255变到50-200).

**Comment by irenjie** [comment]
> 如果你是想问为什么条纹扭曲了，那是因为SUT的形状导致的。如果你是想问为什么SUT上的条纹和屏幕中的不一样，我也没想清楚，关于结构光技术的文章我也没看过多少。我猜可能是因为条纹灰度值范围太大，相机采集不全，导致黑的比白的多或者白的比黑的多，你可以尝试缩小这个灰度值范围(例如从0-255变到50-200).

也可能是屏幕漏光，之前我遇到过，会造成白的比黑的宽。

**Comment by MrwuGohead** [comment]
好的，非常感谢，我这边再试试看看能不能确认具体原因...

**Comment by MrwuGohead** [comment]
好的，非常感谢，我这边再试试看看能不能确认具体原因...
