### ISSUE TITLE
Phase measurement deflection technique-（PMD）-Stereo Deflectometry

### ISSUE THREAD

**Issue by CCCCcccc7** [irenjie/Phase-Measuring-Deflectometry#4]
The whole process code

**Comment by irenjie** [comment]
check dev branch

**Comment by CCCCcccc7** [comment]
>相移法，时间相位展开算法；波前重构法等；
我有一个问题，减参考面法，被测镜相位减掉参考镜相位，他们做差计算精度可达微米甚至纳米，那怎样不用参考镜相位又不改变精度？是用绝对相位？绝对相位不等于展开相位吧？

**Comment by RockyZdx** [comment]
Can I have your email address for the contact as I really want to use this method for some inspection applications?

**Comment by irenjie** [comment]
> > 相移法，时间相位展开算法；波前重构法等；
> > 我有一个问题，减参考面法，被测镜相位减掉参考镜相位，他们做差计算精度可达微米甚至纳米，那怎样不用参考镜相位又不改变精度？是用绝对相位？绝对相位不等于展开相位吧？

我有些没看明白你的问题，如果你是对参考面有疑问，单相机单屏幕的系统计算斜率时，需要一个reference surface帮助计算斜率，我的做法是在待测物位置放置一个平面镜，测量该平面镜的位姿作为reference surface。
